// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./components/Content.vue')['default']
    DocsList: typeof import('./components/DocsList.vue')['default']
    DocsSec: typeof import('./components/DocsSec.vue')['default']
    MenuList: typeof import('./components/MenuList.vue')['default']
  }
}

export { }
