// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    GitHub: typeof import('./components/icons/GitHub.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ListDocs: typeof import('./components/ListDocs.vue')['default']
  }
}

export { }
